<?php

namespace Aizatto\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class UserLogRepository extends EntityRepository
{
}
